version: '3.8'

services:
  # Persistent Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: thesecurex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securex_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - securex-mesh

  portal-gateway:
    build: ./portal-gateway
    container_name: portal-gateway
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/thesecurex
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: securex_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      EVIDENCE_VAULT_PATH: /data/vault
    volumes:
      - ./evidence-vault:/data/vault
    depends_on:
      - db
    networks:
      - securex-mesh

  ai-engine:
    build: ./ai-engine
    container_name: ai-engine
    ports:
      - "8000:8000"
    environment:
      JAVA_PORTAL_URL: http://portal-gateway:8081/api/tools/verify
      VAULT_PATH: /data/vault
    volumes:
      - ./evidence-vault:/data/vault
    depends_on:
      - portal-gateway
    networks:
      - securex-mesh

  network-tools:
    build: ./network-tools
    container_name: network-tools
    ports:
      - "8002:8002"
    environment:
      JAVA_PORTAL_URL: http://portal-gateway:8081/api/tools/verify
      VAULT_PATH: /data/vault
    volumes:
      - ./evidence-vault:/data/vault
    depends_on:
      - portal-gateway
    networks:
      - securex-mesh

networks:
  securex-mesh:
    driver: bridge

volumes:
  postgres_data:
  evidence-vault: